language: shell
dist: xenial
services:
  - docker

install:
  - mkdir -p $HOME/bin
  - curl -sL -o $HOME/bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.17.3/hadolint-Linux-x86_64 && chmod 755 $HOME/bin/hadolint
  - export PATH=$PATH:$HOME/bin
  - sudo apt-get update && sudo apt-get install dnsutils

script:
  - bash test/linters.sh
  - bash test/setup.sh
  - bash test/test.sh
  - bash test/clean.sh

deploy:
  provider: script
  script: echo $DOCKER_PASS | docker login -u selfhostingtools --password-stdin && docker push selfhostingtools/unbound:latest
  on:
    branch: master

notifications:
  email:
    - secure: "XTCQ/FJlR9eJOhCN4RtbtJKfAnIQDR5O2Ijc7qYOmLzd0KQhsgcCJ3diW1IWTI29Sm2nC3hq6R83s3XizD6NGacyZ89yNB92rahehsQOZAT185bRaun9WJNLqcr/jcIKXZ0WZrS1piUD8L0k0Fkhk9lilOMMapAq3ZhwTe82VSBVAogwoBpbZHYWDZRGk54h4f/q5k9IrnHL/yPUQC8ySjQ31YyckfkysCufqhGJzlM9AkxreIF1qV1hxo1C2OmF3PG3jbGh5/M7eoZD/FHnzCpEeyYe5P/fgX8fNYrvm+FHBs8pu1fQWx0lLREzMH6SjMWoqlJ1ATk7jZWuOLjW5UBCcQutSDTY4LAikoWm4TGutlOl+prgOCTzmHzm2tPFoh2QExHUqajxIih4QKMeLTae1DZbsmGW1uwZUXHcqjZ/Xf5PgRTJvJPBMJgYGlLxpmeoEF4i1bIofFZ7gsHUWKSLfjl2jtRws4NVUS9yDvyhrB5jOAK4WjxVPC024kmatcgv+dq98mskd5sZNE2K29tN+E1FvhojHcFEGQo1OTTHpZmyUv0c9CBNf7pjRMYciRYB2oDE/FXCwcBTNI825eFOv4GU9MhjHV/0HGGaofBnBXMlrvhyRsiGgLvLXgAlxKgy/GumeCMXABD5850xI/pw/dzsxmCpnLay2H18Z6k="
